### ISSUE TITLE
In Angular 1.4.7 images do not scale back down

### ISSUE THREAD

**Issue by m-torin** [uttesh/ngreactions#1]
Great concept! I'm using Angular 1.4.7 with your demo code and the image classes are not being removed. Does this happen for you or am I likely missing something?

Thanks!

<img width="252" alt="screen shot 2015-11-22 at 2 39 55 pm" src="https://cloud.githubusercontent.com/assets/645847/11325850/ec090606-9126-11e5-8952-d0bb38501e47.png">

**Comment by uttesh** [comment]
@mattrepublic thanks for the input, i did not had any issue if possible could you please provide me the steps to reproduce or put the code in codepen that will help me to rectify the issue.
